apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nvidia-device-plugin-daemonset.yaml
  - dcgm-exporter-daemonset.yaml
  - dcgm-exporter-service.yaml
  - dcgm-exporter-servicemonitor.yaml
