apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm-exporter
  namespace: gpu-operator
  labels:
    app.kubernetes.io/name: nvidia-dcgm-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nvidia-dcgm-exporter
  ports:
    - name: gpu-metrics
      port: 9400
      targetPort: gpu-metrics
      protocol: TCP
